# Generated by Django 2.1.7 on 2019-12-01 15:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CEM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montoPago', models.FloatField()),
                ('fechaPago', models.DateTimeField(default=datetime.datetime(2019, 12, 1, 9, 13, 46, 619080))),
                ('idDoctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CEM.Doctor')),
            ],
        ),
    ]
