# Generated by Django 2.1.7 on 2019-11-22 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CEM', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montoPago', models.FloatField()),
                ('fechaPago', models.DateField()),
                ('idDoctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CEM.Doctor')),
            ],
        ),
    ]
