# Generated by Django 2.1.7 on 2019-11-24 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conntabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fechaPago',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 23, 23, 59, 31, 932537)),
        ),
    ]
