# Generated by Django 2.1.7 on 2019-11-30 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conntabilidad', '0002_auto_20191123_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fechaPago',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 30, 12, 39, 57, 329981)),
        ),
    ]
