# Generated by Django 2.1.7 on 2019-12-01 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conntabilidad', '0002_auto_20191123_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fechaPago',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 1, 14, 1, 36, 200167)),
        ),
    ]
