# Generated by Django 2.1.7 on 2019-12-01 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conntabilidad', '0004_auto_20191201_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fechaPago',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 1, 14, 11, 29, 508083)),
        ),
    ]
