# Generated by Django 2.1.7 on 2019-12-02 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conntabilidad', '0005_auto_20191201_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fechaPago',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 1, 22, 46, 33, 454175)),
        ),
    ]
