# Generated by Django 2.1.7 on 2019-09-24 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CEM', '0002_auto_20190907_2225'),
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='idDoctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CEM.Doctor'),
        ),
    ]
