# Generated by Django 2.1.7 on 2019-10-02 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CEM', '0003_doctor_user'),
        ('calendario', '0002_event_iddoctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='expediente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CEM.Paciente'),
        ),
    ]
