# Generated by Django 2.1.7 on 2019-06-11 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('idConsulta', models.AutoField(primary_key=True, serialize=False)),
                ('fechaConsulta', models.DateField()),
                ('pesoConsulta', models.IntegerField(blank=True)),
                ('presionConsulta', models.CharField(blank=True, max_length=10)),
                ('temperatura', models.IntegerField(blank=True)),
                ('pulso', models.IntegerField(blank=True)),
                ('alturaConsulta', models.IntegerField(blank=True)),
                ('observaciones', models.TextField(max_length=500)),
                ('recetas', models.TextField(blank=True, max_length=200)),
                ('examenesSolicitados', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('idDoctor', models.AutoField(primary_key=True, serialize=False)),
                ('primerNombreDoctor', models.CharField(max_length=50)),
                ('segundoNombreDoctor', models.CharField(blank=True, max_length=50)),
                ('primerApellidoDoctor', models.CharField(max_length=50)),
                ('segundoApellidoDoctor', models.CharField(blank=True, max_length=50)),
                ('especialidad', models.CharField(max_length=50)),
                ('sexoDoctor', models.BooleanField()),
                ('fechaNacimientoDoctor', models.DateField()),
                ('telefonoDoctor', models.CharField(max_length=9)),
                ('correoElectronico', models.CharField(max_length=50)),
                ('duiDoctor', models.CharField(max_length=12)),
                ('fotografiaDoctor', models.ImageField(upload_to='cem/imagenes/doctores/')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediente', models.CharField(max_length=20)),
                ('primerNombrePaciente', models.CharField(max_length=50)),
                ('segundoNombrePaciente', models.CharField(blank=True, max_length=50)),
                ('primerApellidoPaciente', models.CharField(max_length=50)),
                ('segundoApellidoPaciente', models.CharField(blank=True, max_length=50)),
                ('sexoPaciente', models.BooleanField()),
                ('fechaNacimientoPaciente', models.DateField()),
                ('alturaPaciente', models.IntegerField(blank=True)),
                ('pesoPaciente', models.FloatField(blank=True, max_length=5)),
                ('telefonoPaciente', models.CharField(blank=True, max_length=9)),
                ('fotografiaPaciente', models.ImageField(blank=True, upload_to='cem/imagenes/pacientes/')),
                ('institucion', models.CharField(blank=True, max_length=50)),
                ('alergias', models.TextField(blank=True, max_length=200)),
                ('antecedentes', models.TextField(blank=True, max_length=200)),
                ('idDoctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CEM.Doctor')),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CEM.Paciente'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='idDoctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CEM.Doctor'),
        ),
    ]
