# Generated by Django 2.1.7 on 2019-06-15 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaConsulta', models.DateField()),
                ('pesoConsulta', models.IntegerField(blank=True, null=True)),
                ('presionConsulta', models.CharField(blank=True, max_length=10, null=True)),
                ('temperatura', models.IntegerField(blank=True, null=True)),
                ('pulso', models.IntegerField(blank=True, null=True)),
                ('alturaConsulta', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(max_length=500)),
                ('recetas', models.TextField(blank=True, max_length=200, null=True)),
                ('examenesSolicitados', models.TextField(blank=True, max_length=200, null=True)),
                ('reporteExamenes', models.TextField(blank=True, max_length=200, null=True)),
                ('fechaUltimaRegla', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primerNombreDoctor', models.CharField(max_length=50)),
                ('segundoNombreDoctor', models.CharField(blank=True, max_length=50, null=True)),
                ('primerApellidoDoctor', models.CharField(max_length=50)),
                ('segundoApellidoDoctor', models.CharField(blank=True, max_length=50, null=True)),
                ('especialidad', models.CharField(max_length=50)),
                ('sexoDoctor', models.BooleanField()),
                ('fechaNacimientoDoctor', models.DateField()),
                ('telefonoDoctor', models.CharField(max_length=9)),
                ('correoElectronico', models.CharField(max_length=50)),
                ('duiDoctor', models.CharField(max_length=12)),
                ('nitDoctor', models.CharField(max_length=20)),
                ('ncfDoctor', models.CharField(max_length=15)),
                ('fotografiaDoctor', models.ImageField(blank=True, null=True, upload_to='doctores')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediente', models.CharField(max_length=20)),
                ('primerNombrePaciente', models.CharField(max_length=50)),
                ('segundoNombrePaciente', models.CharField(blank=True, max_length=50, null=True)),
                ('primerApellidoPaciente', models.CharField(max_length=50)),
                ('segundoApellidoPaciente', models.CharField(blank=True, max_length=50, null=True)),
                ('sexoPaciente', models.BooleanField()),
                ('fechaNacimientoPaciente', models.DateField()),
                ('alturaPaciente', models.IntegerField(blank=True, null=True)),
                ('pesoPaciente', models.FloatField(blank=True, max_length=5, null=True)),
                ('telefonoPaciente', models.CharField(blank=True, max_length=9, null=True)),
                ('fotografiaPaciente', models.ImageField(blank=True, null=True, upload_to='cem/imagenes/pacientes/')),
                ('institucion', models.CharField(blank=True, max_length=50, null=True)),
                ('aseguradora', models.CharField(blank=True, max_length=50, null=True)),
                ('alergias', models.TextField(blank=True, max_length=200)),
                ('lugarProveniencia', models.CharField(blank=True, max_length=100, null=True)),
                ('tabquista', models.BooleanField()),
                ('etilista', models.BooleanField()),
                ('hipertenso', models.BooleanField()),
                ('diabetico', models.BooleanField()),
                ('tuberculosis', models.BooleanField()),
                ('anemia', models.BooleanField()),
                ('convulsiones', models.BooleanField()),
                ('cancer', models.BooleanField()),
                ('lugarCancer', models.CharField(blank=True, max_length=50, null=True)),
                ('tratamientoCancer', models.CharField(blank=True, max_length=100, null=True)),
                ('antecedentes', models.TextField(blank=True, max_length=200)),
                ('doctores', models.ManyToManyField(to='CEM.Doctor')),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='expediente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CEM.Paciente'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='idDoctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CEM.Doctor'),
        ),
    ]
