# Generated by Django 2.1.7 on 2019-06-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CEM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='alturaConsulta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='examenesSolicitados',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='pesoConsulta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='presionConsulta',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='pulso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='recetas',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='temperatura',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
