# Generated by Django 2.1.7 on 2019-06-12 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CEM', '0003_auto_20190611_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='fotografiaDoctor',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
