# Generated by Django 2.1.7 on 2019-06-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CEM', '0005_auto_20190611_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='id',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='expediente',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
