# Generated by Django 2.1.7 on 2019-06-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CEM', '0006_auto_20190613_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='alturaPaciente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='pesoPaciente',
            field=models.FloatField(blank=True, max_length=5, null=True),
        ),
    ]
