# Generated by Django 2.1.7 on 2019-06-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CEM', '0007_auto_20190613_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='idDoctor',
        ),
        migrations.AddField(
            model_name='consulta',
            name='fechaUltimaRegla',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='reporteExamenes',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='ncfDoctor',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='nitDoctor',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='anemia',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='aseguradora',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cancer',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='convulsiones',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='diabetico',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='doctores',
            field=models.ManyToManyField(to='CEM.Doctor'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='etilista',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='hipertenso',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='lugarCancer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='lugarProveniencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tabquista',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='tratamientoCancer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tuberculosis',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='fotografiaDoctor',
            field=models.ImageField(blank=True, null=True, upload_to='doctores'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='segundoApellidoDoctor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='segundoNombreDoctor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fotografiaPaciente',
            field=models.ImageField(blank=True, null=True, upload_to='cem/imagenes/pacientes/'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='institucion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='segundoApellidoPaciente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='segundoNombrePaciente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefonoPaciente',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
